biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('usuario.urls')),
    path("emprestimo/", include('emprestimo.urls')),
    path("livro/", include('livro.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devolver/urls.py
from django.urls import path
from . import views

app_name = 'devolucao'


urlpatterns = [
    path('devolver/', views.devolver, name="devolver"),
]

emprestimo/urls.py
from django.urls import include, path
from . import views

app_name = 'emprestimo'

urlpatterns = [
    path('', views.MeusEmprestimos.as_view(), name='meus_emprestimos'),
    path('emprestar/', include('emprestar.urls', namespace='emprestar')),
    path('devolver/', include('devolver.urls', namespace='devolver')),
]

livro/urls.py
from django.urls import path
from .views import ListaLivros, DetalhesLivro

app_name = 'livro'

urlpatterns = [
    path('lista/', ListaLivros.as_view(), name="home"),
    path('detalhes/<int:pk>/', DetalhesLivro.as_view(), name = 'detalhes')
]

emprestimo/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User


import sys
import os


sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from livro.models import Livro
from usuario.models import Usuario

class Emprestimo(models.Model):
    nome_estudante = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING, null=True, blank=True)
    livro_emprestar = models.ForeignKey(Livro, on_delete=models.DO_NOTHING, null=True, blank=True)
    data_emprestimo = models.DateTimeField(default=timezone.now)
    data_devolucao = models.DateTimeField(blank=True, null=True)
    entrega_atrasada = models.BooleanField(default=False)
    taxa = models.CharField(default="R$0,00", max_length=8)

    def __str__(self) -> str:
        return f'{self.livro_emprestar} emprestado com sucesso!'    

emprestimo/forms.py
from django import forms
from .models import Emprestimo

class EmprestimoForm(forms.ModelForm):
    class Meta:
        model = Emprestimo
        fields = '__all__'

emprestimo/views.py
from pyexpat.errors import messages
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required

import sys
import os

from emprestimo.models import Emprestimo
from usuario.models import Usuario

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from .mixins import MeusEmprestimosMixin, TodosEmprestimosMixin
 
class ListarEmprestimos(TodosEmprestimosMixin, ListView):
    model = Emprestimo
    context_object_name = 'emprestados'
    template_name = 'emprestimo/meus_emprestimos.html'
    paginate_by = 6
    ordering = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # emprestimos_atrasados = Emprestimo.objects.filter(data_devolucao__lt=self.model.data_devolvido)
        # context['emprestimos_atrasados'] = emprestimos_atrasados

        return context
    
class MeusEmprestimos(MeusEmprestimosMixin, ListView):
    model = Emprestimo
    template_name = 'emprestimo/meus_emprestimos.html'
    context_object_name = 'emprestimos'

    def get_queryset(self):
        estudante = Usuario.objects.get(usuario_id=self.request.user)
        return Emprestimo.objects.filter(nome_estudante=estudante)
    

emprestimo/templates/emprestimo/emprestados.html
{% extends "base.html" %}
{% load filters %}

{% block conteudo %}
<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Data Empréstimo</th>
                <th scope="col">Data Devolução</th>
                <th scope="col">Disponibilidade</th>
                <th scope="col">Devolver</th>
            </tr>
        </thead>
        <tbody>
            <form action="{% url 'emprestimo:devolver' %}" method="POST">
                {% csrf_token %} 
                {% for livro in emprestados %}
                <tr>
                    <th scope="row">{{ livro.id }}</th>
                    <td>{{livro.nome_estudante}}</td>
                    <td>{{livro.data_emprestimo}}</td>
                    <td>{{livro.data_devolucao}}</td>
                    <td>            
                        {% if livro.emprestado %}
                            <h6>Indisponível</h6>
                        {% else %}
                            <h6>Disponível</h6>
                        {% endif %}
                    </td>
                    <input type="hidden" name="id" value="{{ livro.id }}">
                    <input type="hidden" name="livro_emprestar_id" value="{{ livro.livro_emprestar_id }}">
                    <td>
                        <button type="submit" class="btn btn-secondary">Devolver</button>
                    </td>
                </tr>
                {% endfor %}
            </form>
        </tbody>
    </table>
</div>
{% endblock %}

emprestimo/templates/emprestimo/meus_emprestimos.html
{% extends "base.html" %}
{% load filters %}

{% block body_class %}home-background{% endblock %}

{% block conteudo %}
<div id="card_hist" class="card_hist">
    <div class="card-body-hist">
        <div class="card-title_hist">
            <h3>Meus empréstimos</h3>
        </div>
        <div class="card-text">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Livro</th>
                        <th scope="col">Data Empréstimo</th>
                        <th scope="col">Data Devolução</th>
                        <th scope="col">Disponibilidade</th>
                        <th scope="col">Devolver</th>
                    </tr>
                </thead>
                <tbody>
                    {% for livro in emprestimos %}
                    <form action="{% url 'emprestimo:devolucao:devolver' %}" method="POST">
                        {% csrf_token %} 
                        <tr>
                            <th scope="row">{{ livro.id }}</th>
                            <td><a href="{% url 'livro:detalhes' livro.livro_emprestar_id %}" class="detalhe_livro">{{ livro.livro_emprestar_id }}
                            </a>
                            </td>
                            <td>{{ livro.data_emprestimo }}</td>
                            {% if not livro.data_devolucao %}
                                <td>
                                    <h5>X</h5>
                                </td>
                                <td>
                                    <h6>Emprestado</h6>
                                </td>
                                <td id="botao_devolver">
                                    <button type="submit" id="botao" class="btn">Devolver</button>
                                </td>
                                {% else %}
                                <td>
                                    {{ livro.data_devolucao }}
                                </td>
                                <td>
                                    <h6>Disponível</h6>
                                </td>
                                <td>
                                    <h6>Devolvido</h6>
                                </td>  
                                {% endif %}
                            <input type="hidden" name="id" value="{{ livro.id }}">
                            <input type="hidden" name="first_name" value="{{ livro.nome_estudante }}">
                            <input type="hidden" name="nome_estudante" value="{{ request.user.id }}">
                            <input type="hidden" name="livro_emprestar_id" value="{{ livro.livro_emprestar_id }}">
                        </tr>
                    </form>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>    
</div>
{% endblock %}