biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('usuario.urls')),
    path("emprestimo/", include('emprestimo.urls')),
    path("livro/", include('livro.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emprestimo/urls.py
from django.urls import include, path
from . import views

app_name = 'emprestimo'

urlpatterns = [
    path('', views.MeusEmprestimos.as_view(), name='meus_emprestimos'),
    path('emprestar/', include('emprestar.urls', namespace='emprestar')),
    path('devolver/', include('devolver.urls', namespace='devolver')),
]

livro/urls.py
from django.urls import path
from .views import ListaLivros, DetalhesLivro

app_name = 'livro'

urlpatterns = [
    path('lista/', ListaLivros.as_view(), name="home"),
    path('detalhes/<int:pk>/', DetalhesLivro.as_view(), name = 'detalhes')
]

usuario/urls.py
from django.urls import path
from .views import Cadastrar, Atualizar, UserLogin, Logout

app_name="usuario"

urlpatterns = [
    path('', UserLogin.as_view(), name="login"),
    path('cadastrar/', Cadastrar.as_view(), name="cadastrar"),
    path('atualizar/', Atualizar.as_view(), name="atualizar"),
    path('logout/', Logout.as_view(), name="logout"),
]

templates/parciais/_footer.html
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

<footer id="fixed-footer" class="rodapel">
    <div class="container">
        <div class="texto_django" style="color: white; text-align: center">
            <b>Feito com Django</b>
        </div>
        <div class="texto_autor" style="color: white">
            <b>Por Gabriel Ferreira</b>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>

templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/livro.css' %}">
<link rel="stylesheet" href="{% static 'css/usuario.css' %}">
{% endblock %}

templates/parciais/_messages.html
{% if messages %}
    <div class="messages-container">
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/parciais/_navbar.html
{% load static %}

<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
    <div class="img_logo">
        <a class="titulo" href="{% url 'livro:home' %}"><img src="{% static 'img/Capa_Logo.jpg' %}" alt="" style="width: 45px; height: 60px;"></a>
    </div>
    <div class="menu">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="botoes_navbar">
        <div class="meus_itens">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'emprestimo:meus_emprestimos' %}">Meus livros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'usuario:cadastrar' %}">Meu perfil</a>
                </li>
                {% endif %}
            </ul>
        </div>
        {% comment %} <form method="GET" action="{% url 'produto:busca' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="termo" value="{{ request.GET.termo }}" type="search" placeholder="Pesquisar" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Pesquisar</button>
        </form> {% endcomment %}
    </div>
    {% if request.user.is_authenticated %}
    <div class="boasvindas">
        <p id="texto_bemvindos">Seja bem vindo(a) {{ request.user.first_name }} - {{ request.user.usuario.matricula }}</p>    
    </div>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">    
            <a id="texto_sair" class="nav-link active" href="{% url 'usuario:logout' %}">Sair</a>
        </li>
    </ul>
    {% else %}
    <div class="cadastrar_botoes">
        <a id="botao" class="btn" href="{% url 'usuario:cadastrar' %}">Cadastrar</a>
        <a id="botao" class="btn" href="{% url 'usuario:login' %}">Entrar</a>
    </div>
    {% endif %}
</nav>

templates/parciais/_pagination.html
{% if is_paginated %}

<div class="col mt-3 mb-3">
    <div class="row">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}